sudo: required
services:
  - docker

before_install:
  - docker build -t seammour/multi-container-test -f ./client/Dockerfile.dev ./client

script:
  - docker run seammour/multi-container-test npm run test -- --coverage

after_success:
    - docker build -t ammour76/multi-container-client ./client
    - docker build -t ammour76/multi-container-nginx ./nginx
    - docker build -t ammour76/multi-container-server ./server
    - docker build -t ammour76/multi-container-worker ./worker
    # log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push ammour76/multi-container-client
    - docker push ammour76/multi-container-nginx
    - docker push ammour76/multi-container-server
    - docker push ammour76/multi-container-worker